### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Zenopheus** [MrNobody98/morecommands#3]
MoreCommands-1.7.10-1.6.java
Minecraft 1.7.10 w/Forge 1566.

Without this mod:
1. Load an existing world
2. Let it rest for 2 min
3. Launch VisualVM
4. CPU idles at 18%

With this mod:
1. Load an existing world
2. Let it rest for 2 min
3. Launch VisualVM
4. CPU idles at 42%

**Comment by MrNobody98** [comment]
I figured out the source of this performance issue and I can offer you a hotfix. However this will result in not being able to use the "infiniteitems" command anymore and giving up the automatic handshake redo mechanism (if you don't know what I mean, read this: http://morecommands.bplaced.net/morecommands/usage/settings.html)

1. Go to your .minecraft/config/morecommands folder
2. Open the file settings.cfg
3. There's a line called "retryHandshake=true", change it to "retryHandshake=false"
4. Open the mod jar file with winrar, 7zip or whatever
5. Navigate to the folder com/mrnobody/morecommands/command/server
6. Delete those 4 files from the folder:
    - CommandInfiniteitems$1.class
    - CommandInfiniteitems$Stack.class
    - CommandInfiniteitems$StackObserver.class
    - CommandInfiniteitems.class

This should reduce the CPU usage drastically. By following these two steps, two threads are prevented from running, I didn't realize that their CPU usage was so high... I will fix these performance issues in the next release as good as it's possible but such a rather not so urgently necessary fix doesn't justify releasing a completly new version. I need some more stuff for a new verson, e.g. some new commands, I already have some ideas. If the changes to be made for a new version are enough I will release that new version. In the meantime you have to be satisfied with that hotfix but I think that should do it aswell.

I hope this helps but if it doesn't, feel free to write again!

**Comment by Zenopheus** [comment]
I just tested it, the CPU is back to normal. Thanks!
BTW: I think if you change the ConcurrentLinkedQueue (CommandInfiniteitems.java:80) to a LinkedBlockingQueue then replace the poll() (CommandInfiniteitems.java:61) to a take() you'll be good.   take() blocks when the queue is empty. Thanks for your time!

**Comment by MrNobody98** [comment]
You're right, a blocking queue is definitely the better alternative (concurrency is not really my specialty) and increases performance but still has a negative impact. I think I'll try to figure out a new approach to implement the infiniteitems command because a whole thread for one command is a bit too much. The reason why I made this was because Forge reverts all changes made to the item stack in PlaceEvent. But there's a reason why forge does this which I haven't considered too: the stack size changes client side too so server and client get out of sync. I will reimplement that command correctly (maybe using asm to post a custom ItemStackChangeSizeEvent or something like that) so it won't make the item stack de-synchronized and won't affect performance in such a bad way.

**Comment by Zenopheus** [comment]
Sounds good. I write a lot of concurrent code for a living but u don't know
much about mod code  thanks again.
