### ISSUE TITLE
1.12.2 problem or two

### ISSUE THREAD

**Issue by LoRaM100** [MrNobody98/morecommands#6]
Morning my friend, I hope you're in good health and the Gods are smiling on you. 
A couple of problems with the current MoreCommands and 1.12.2. 
1. You cannot enter a minecart or boat, nor can you fish. 
2. minor problem, the /speed command returns an error and no longer works. I don't think it worked with any 1.12 version. 
Thanks 
Lou

**Comment by MrNobody98** [comment]
Well, I didn't feel like doing anything in terms of minecraft the last 1-2 months so I haven't even checked if there's a new minecraft version at all (that's also why I didn't respond to your message in the MC forums - sorry for that).

About those problems:
I tested both minecart/boat/fishing and the speed command with MC 1.12 and everything works for me. However, I'm surprised that the 1.12 version works for 1.12.1 and 1.12.2 since there are indeed some small changes (actually it's really only one or two lines of code) which require an update of MoreCommands. I guess it works because these changes are part of the network code and minecraft does heavy error-catching (which is fine, networking stuff can easily produce errors, e.g. if internet connection is lost) so that error was probably quietly caught instead of crashing the game but not handled properly which is why you experience these issues.

I updated the 1.12 version for 1.12.1 and 1.12.2 and they should work without problems (tested it and everything works):

1.12.1: http://www.mediafire.com/file/tyrg1xzfrwhh6gv/MoreCommands-1.12.1-6.0.jar
1.12.2: http://www.mediafire.com/file/jo5kbvav0joox5q/MoreCommands-1.12.2-6.0.jar
