### ISSUE TITLE
1.12.2 again

### ISSUE THREAD

**Issue by LoRaM100** [MrNobody98/morecommands#7]
I just tried again... 
I added the new 12.2 to my 12.2 mods folder and tried to open it... It does open, I can select a world (even created a new one) it says loading, then I get a brown screen with a 0% in it and nothing more happens. I tried it with just Forge (no LiteLoader or those mods), same thing. Vanilla loads as does 12.0. 
I think it's the same with 1.12.1, I did not test as in depth as 12.2. 
Lou
Also /ignorespawn isn't working with 12.0 MoreCommands. Odds are good a working 1.12.2 will fix all my problems.

**Comment by MrNobody98** [comment]
I figured out what that was - It was a bug in ForgeGradle, Forge's build system, which caused inproper reobfuscation for release versions so I didn't notice that bug because I'm working with the deobfuscated version in a development environment and that bug only appeared in the final obfuscated release version.

Luckily, the Forge devs updated ForgeGradle (I was actually in the process of doing a workaround to avoid this bug when the fixed version came out and I had to undo that workaround) and I've rebuilt MoreCommands to get rid of this issue. You can download the updated verions, links are the same.

Also, I'm not sure if your /ignorespawn problem was caused by this too but I think so because it's working fine for me now. If there are still issues with that command, just report them here and I'll have a closer look.
