### ISSUE TITLE
Getting a crash in 1.12.2 with More Commands 6.0

### ISSUE THREAD

**Issue by BrisingrAerowing** [MrNobody98/morecommands#8]
[Crash Log](https://gist.github.com/BrisingrAerowing/7eb26808fdb11cafcec442c210f739c1)

Something is broken. It might be another mod I use goofing things, as I haven't seen anyone else mention this.

**Comment by MrNobody98** [comment]
After some investigation I figured out the following things:

First, the actual crash is not caused by MoreCommands itself. If you have a look at the crash report, there's a chain of "caused by" clauses:

Caused by: java.lang.NoClassDefFoundError: net/minecraft/network/NetHandlerPlayServer
...
...
...
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method localvar$onPlayerDigging$zze000(D)D in mixins.malisiscore.core.json:MixinChunkCollision$MixinNetHandlerPlayServer failed injection check, (0/1) succeeded. Using refmap mixins.malisiscore.refmap.json

What this says is that the "NetHandlerPlayServer" class couldn't be loaded because a transformation of this class done by "mixins.malisiscore.core.json:MixinChunkCollision$MixinNetHandlerPlayServer" failed so the class couldn't be loaded. This means that MoreCommands is simply the first place where the "NetHandlerPlayServer" class is used so it should simply crash at later point without MoreCommands except if somehow some changes made by MoreCommands cause the transformation to fail. However, this can't actually be the case because MoreCommands doesn't do any changes related to this tranformation.

I digged a bit into this and it seems that there was indeed a bug in the Mixin Framework (https://github.com/SpongePowered/Mixin/issues/209) used by MalisisCore (which caused the failure to load the "NetHandlerPlayServer" class) and also in MalisisCore itself. However, this was fixed and the code for the version you use is correct and should work properly.

So I thought I'll try it for myself. I've set up a clean Minecraft installation with only MoreCommands and MalisisCore and everything worked fine, no crashes or bugs at all.

The only thing I can imagine to be causing this is either: A third mod interferes but doesn't show up in the log or there's a version issue since SpongeForge 1.12 was developed with Forge 14.23.0.2503 so maybe there's a change which causes problems although that seems unlikely since you use a newer version (and I think MalisisCore uses only the Mixin Framework and not the entire SpongeForge API).

Try the following things:
- Try launching Minecraft without MoreCommands and load up a world (this is important!). Does it work?
- Try launching Minecraft only with MalisisCore and MoreCommands. Does that work?
- Try using Forge 14.23.0.2503. Does that fix anything?

Finally if nothing helps, you could try to set up a clean Minecraft installation and re-download your mods (MalisisCore and MoreCommands should be enough) to make sure everything's up-to-date. If even that doesn't help, I'm clueless what else it could be because as I said, I have no issues at all.

**Comment by BrisingrAerowing** [comment]
I did some research with what you said, and it is an incompatibility between MalisisCore and LiteLoader. I have one LiteLoader mod for fullbright, so I'll remove that and LL for now.

**Comment by SKYMEE1** [comment]
It can also happen without any mod that requires LiteLoader. You don't need malisiscore.jar but in my case and I think in most cases it will help to install Forge 14.23.0.2503 as mentioned above. 
So just that it's clear what will definitley help.
