### ISSUE TITLE
XRay JSON serializer not working properly

### ISSUE THREAD

**Issue by vveider** [MrNobody98/morecommands#9]
After creating and saving corresponding configuration:
```
xray on
xray config
xray save lava
```

there is empty setting for xray at `settings_client.json`:
```json
"xray": {
    "server": "singleplayer",
    "value": {}
  }
```

Thus saving of xray presets not working.

Also did not find any manual about correct xray JSON configuration format to enter it manually.

**Comment by MrNobody98** [comment]
I forgot to add the colors to the "value" field so that's why it didn't work properly. I fixed it (and did some other changes too), just redownload the mod.

Also, to add presets manually, you just have to change the "value" property with the following structure:
The "value" property must be a JSON object which maps the preset names (the keys of that object) to the actual presets. A preset itself again is a JSON object which has exactly two entries. The first one is named "radius" which must be a number and specifies the xray radius. The second one is "colors" and must be a JSON object again. This JSON object maps the actual blocks (minecraft names) to the color to use. The color itself is represented as it is done in HTML/CSS: A hex-string starting with "#" and then the color RGB value as hex value.

For Example:
`"xray": {
    "server" : "singleplayer",
    "value" : {
        "lava" : {
            "radius" : 32,
            "colors" : {
                "minecraft:lava" : "#0EFF6C",
                "minecraft:flowing_lava" : "#0EFF6C"
            }
        },
       "iron" : {
          "radius" : 50,
          "colors" : {
              "minecraft:iron_ore" : "#A785FE"
          }
       }
    }
}`

You can find color pickers online, just google "html color picker", also you can omit the "minecraft:" prefix for minecraft blocks but when you want to use blocks of other mods, you need to prefix the mod id, e.g. "somemod:ablock".

If you think that xray updates to slowly (By default, the highlighted blocks are updated once per second), you can change that in the "config.cfg" file and change the entry "xrayUPS" to the amount of updates per second you want to have (max. 10 per second)

Lastly, I added the "/xray load_combined" command which loads a preset without unloading the previous preset, so you can combine presets.
I also added "/xray reset" which de-highlights all blocks since it's tedious to do that manually using the config.
